---
- name: Update Argo CD and Jenkins admin passwords on Minikube
  hosts: localhost
  become: yes

  vars_prompt:
    - name: cluster_name
      prompt: "Enter your targeted cluster name"

    - name: argocd_new_password
      prompt: "Enter the new Argo CD admin password"
      private: yes

    - name: jenkins_new_password
      prompt: "Enter the new Jenkins admin password"
      private: yes
  
  pre_tasks:
    - name: Check if Minikube cluster is already running
      command: minikube status -p {{ cluster_name }}
      register: minikube_status
      ignore_errors: true
      changed_when: false
      become: false

    - name: Start Minikube cluster if not running
      command: minikube start -p {{ cluster_name }} --driver={{ minikube_driver }} --force
      when: "'Running' not in minikube_status.stdout"
      become: false

  tasks:
    - name: Retrieve Argo CD initial admin password (Base64 encoded)
      command: >
        kubectl -n argocd get secret argocd-initial-admin-secret
        -o jsonpath={.data.password}
      register: argocd_secret_b64

    - name: Decode and set current Argo CD password
      set_fact:
        argocd_current_password: "{{ argocd_secret_b64.stdout | b64decode }}"

    - name: Get Argo CD server URL
      command: >
        minikube service argocd-server --url -n argocd
      register: argocd_url
      changed_when: false

    - name: Login to Argo CD with CLI
      command: >
        argocd login {{ argocd_url.stdout }}
        --username admin
        --password "{{ argocd_current_password }}"
        --insecure
      environment:
        ARGOCD_OPTS: "--insecure"
      register: argocd_login
      failed_when: argocd_login.rc != 0

    - name: Update Argo CD admin password via CLI
      command: >
        argocd account update-password
        --account admin
        --current-password "{{ argocd_current_password }}"
        --new-password "{{ argocd_new_password }}"
      environment:
        ARGOCD_OPTS: "--insecure"

    - name: Patch Jenkins Secret to update admin password
      command: >
        kubectl -n jenkins patch secret jenkins
        -p '{"stringData":{"jenkins-admin-password":"{{ jenkins_new_password }}"}}'

    - name: Rollout restart Jenkins Deployment
      command: >
        kubectl -n jenkins rollout restart deployment jenkins

    - name: Display completion message
      debug:
        msg: "Argo CD and Jenkins admin passwords have been updated and deployments restarted."