---
- name: Start Minikube tunnel and update admin passwords for Argocd, Jenkins, Nexus, Redis, and RabbitMQ
  hosts: localhost
  vars:
    minikube_driver: docker
  vars_prompt:
    - name: cluster_name
      prompt: "Enter your Minikube cluster name"
      private: false

    - name: all_tools_password
      prompt: "Enter new all tools admin password"
      private: yes

    - name: sudo_password
      prompt: "Enter your sudo password to start tunnel"
      private: yes

  tasks:
    - name: Launch tmux session for Minikube tunnel
      become: yes
      become_method: sudo
      command: >
        tmux new-session -d -s minikube-tunnel "minikube tunnel -p {{ cluster_name }}"

    - name: Wait for tunnel to establish
      pause:
        seconds: 5

    # Argocd
    - name: Retrieve Argocd initial admin password
      command: >
        kubectl -n argocd get secret argocd-initial-admin-secret
        -o jsonpath={.data.password}
      register: argocd_secret_b64

    - name: Decode Argocd current password
      set_fact:
        argocd_current_password: "{{ argocd_secret_b64.stdout | b64decode }}"

    - name: Get Argocd server external IP
      command: >
        kubectl -n argocd get svc argocd-server
        -o jsonpath={.status.loadBalancer.ingress[0].ip}
      register: argocd_host

    - name: Get Argocd server port
      command: >
        kubectl -n argocd get svc argocd-server
        -o jsonpath={.spec.ports[0].port}
      register: argocd_port

    - name: Set Argocd URL fact
      set_fact:
        argocd_url: "{{ argocd_host.stdout }}:{{ argocd_port.stdout }}"

    - name: Login to Argocd CLI
      command: >
        argocd login {{ argocd_url }}
        --username admin
        --password "{{ argocd_current_password }}"
        --insecure

    - name: Update Argocd admin password
      command: >
        argocd account update-password
        --account admin
        --current-password "{{ argocd_current_password }}"
        --new-password "{{ all_tools_password }}"
      environment:
        ARGOCD_OPTS: "--insecure"

    - name: Restart Argocd server deployment
      command: kubectl -n argocd rollout restart deployment argocd-server

    # Jenkins
    - name: Patch Jenkins admin password secret
      command: >
        kubectl -n jenkins patch secret jenkins
        -p '{"stringData":{"jenkins-admin-password":"{{ all_tools_password }}"}}'

    - name: Restart Jenkins deployment
      command: kubectl -n jenkins rollout restart deployment jenkins

    # Nexus
    - name: Patch Nexus admin password secret
      command: >
        kubectl -n nexus patch secret nexus
        -p '{"stringData":{"nexus-admin-password":"{{ all_tools_password }}"}}'

    - name: Restart Nexus deployment
      command: kubectl -n nexus rollout restart deployment nexus

    # Redis
    - name: Patch Redis password secret
      command: >
        kubectl -n redis patch secret redis
        -p '{"stringData":{"redis-password":"{{ all_tools_password }}"}}'

    - name: Restart Redis statefulset
      command: kubectl -n redis rollout restart statefulset redis

    # RabbitMQ
    - name: Patch RabbitMQ password secret
      command: >
        kubectl -n rabbitmq patch secret rabbitmq
        -p '{"stringData":{"rabbitmq-password":"{{ all_tools_password }}"}}'

    - name: Restart RabbitMQ statefulset
      command: kubectl -n rabbitmq rollout restart statefulset rabbitmq

    # Cleanup: Close Minikube tunnel
    - name: Close Minikube tunnel tmux session
      command: tmux kill-session -t minikube-tunnel

    - name: Display completion message
      debug:
        msg: "Admin passwords updated and Minikube tunnel closed successfully."