apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sampleapi.fullname" . }}
  labels:
    app: {{ include "sampleapi.fullname" . }}
spec:
  {{- if .Values.global.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit }}
  {{- end }}
  {{- if .Values.global.replicaCount }}
  replicas: {{ .Values.global.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "sampleapi.fullname" . }}
  strategy:
    type: {{ .Values.global.strategy.type}}
    rollingUpdate:
      maxSurge: {{ .Values.global.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.global.strategy.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      labels:
        app: {{ include "sampleapi.fullname" . }}
    spec:
      containers:
      - name: {{ include "sampleapi.fullname" . }}
        image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.global.service.targetPort }}
        env:
        {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote}}
        {{- end }}
        resources:
          requests:
            cpu: "{{ .Values.global.resources.requests.cpu }}"
            memory: "{{ .Values.global.resources.requests.memory }}"
        livenessProbe:
          httpGet:
            path: {{ .Values.global.livenessProbe.path | quote }}
            port: {{ .Values.global.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.global.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.global.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.global.readinessProbe.path | quote }}
            port: {{ .Values.global.readinessProbe.port }}
          initialDelaySeconds: {{ .Values.global.readinessProbe.initialDelaySeconds}}
          timeoutSeconds: {{ .Values.global.readinessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.global.readinessProbe.periodSeconds }}