apiVersion: v1
kind: Service
metadata:
  name: {{ include "sampleapi.fullname" . }}
spec:
  type: {{ .Values.global.service.type }}
  selector:
    app: {{ include "sampleapi.fullname" . }}
  ports:
  - name: http
    port: {{ .Values.global.service.port }}
    targetPort: {{ .Values.global.service.targetPort }}
    protocol: TCP
{{- if .Values.global.service.nodePort -}}
    nodePort: {{ .Values.global.service.nodePort }}
{{- end -}}