apiVersion: v1
kind: Service
metadata:
  name: {{ include "sampleapi.fullname" . }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "sampleapi.fullname" . }}
  ports:
  - name: http
    port: 8083
    targetPortL: 8082
    protocol: TCP