apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"policy.csv":"g, argo-account, role:admin\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2025-06-04T09:01:08Z","labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd","resourceVersion":"667","uid":"49c04dcc-dd3f-4619-8d33-1fb968ba9834"}}
  creationTimestamp: "2025-06-04T09:01:08Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "21963"
  uid: 49c04dcc-dd3f-4619-8d33-1fb968ba9834
